default:
  name: "MyProxy"
  port: 25590
  password: "mypassword"
  bootstrap:
    - localhost:25591
  # --- Extra options ---
  #
  # enabled: false
  # if you want to disable this socket
  #
  # timeout: 1000
  # delay between each message sending/reading